language: java
jdk: oraclejdk8

script:
  - ./mvnw clean install -B

services:
  - docker

before_install:
  - docker build -t robertreynisson/traviscontainer .
  - docker ps -a

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master