language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - docker build -t robertreynisson/traviscontainer .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master