language: java
jdk: oraclejdk8

services:
  - docker

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=latest
  - export IMAGE_NAME=robertreynisson/traviscontainer
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
  - docker ps -a