language: java
jdk: oraclejdk8

services:
  - docker

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t robertreynisson/traviscontainer .
  - docker run robertreynisson/traviscontainer
  - docker ps -a